name: Build PrisonBreak

on:
  push:
    branches:
      - main
      - master

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository indir
        uses: actions/checkout@v4

      - name: Java 21 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Gradle izin ver
        run: chmod +x gradlew

      - name: Plugin derle
        run: ./gradlew build

      - name: Jar yükle
        uses: actions/upload-artifact@v4
        with:
          name: PrisonBreak
          path: build/libs/*.jar
